/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.epiis.app.presentation;

import com.epiis.app.business.BusinessAppt;
import com.epiis.app.business.BusinessDoctorSpecialty;
import com.epiis.app.business.BusinessEmployee;
import com.epiis.app.business.BusinessPatient;
import com.epiis.app.business.BusinessSpecialty;
import com.epiis.app.dto.DtoDoctorSpecialty;
import com.epiis.app.dto.DtoEmployee;
import com.epiis.app.dto.DtoPatient;
import com.epiis.app.dto.DtoSpecialty;
import com.epiis.app.config.Message;
import java.sql.SQLException;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author LAB306PC10
 */
public class FrmAddAppt extends javax.swing.JInternalFrame {
    BusinessAppt businessAppt = null;
    DtoPatient dtoPatient = null;
    DtoEmployee dtoEmployee = null;
    BusinessEmployee businessEmployee = null;
    BusinessSpecialty businessSpecialty = null;
    BusinessDoctorSpecialty businessDoctorSpecialty = null;
    BusinessPatient businessPatient = null;
    
    /**
     * Creates new form FrmAddAppt
     */
    public FrmAddAppt() {
        this.businessDoctorSpecialty = new BusinessDoctorSpecialty();
        this.businessSpecialty = new BusinessSpecialty();
        this.dtoPatient = new DtoPatient();
        this.businessAppt = new BusinessAppt();
        this.businessEmployee = new BusinessEmployee();
        this.businessPatient = new BusinessPatient();
        initComponents();
        this.init();
    }

    private void init() {
        try {
            comboEsp.removeAllItems();
            List<DtoSpecialty> listSpecialty = businessSpecialty.getAll();
            for (DtoSpecialty spe : listSpecialty) {
                comboEsp.addItem(spe.getName());
            }
            comboEsp.addActionListener(e -> updateDoctorsBySpecialty());

            SpinnerDateModel hourModel = new SpinnerDateModel();
            hourModel.setCalendarField(Calendar.HOUR_OF_DAY);
            hourAppt.setModel(hourModel);
            JSpinner.DateEditor hourEditor = new JSpinner.DateEditor(hourAppt, "HH");
            hourAppt.setEditor(hourEditor);

            updateDoctorsBySpecialty();
        } catch (SQLException e) {
            Message.error(this, e.getMessage());
        }
    }

    private void updateDoctorsBySpecialty() {
        try {
            comboMedico.removeAllItems();
            boolean isMedico = false;
            
            String selectedSpecialty = (String) comboEsp.getSelectedItem();
            if (selectedSpecialty == null) return;

            List<DtoDoctorSpecialty> list = businessDoctorSpecialty.getAll();

            for (DtoDoctorSpecialty ds : list) {
                if (ds.getDtoSpecialty().getName().equals(selectedSpecialty)) {
                    comboMedico.addItem(ds.getDtoEmployee().getFirstName());
                    isMedico = true;
                }
            }
            
            if(!isMedico){
                comboMedico.addItem("sin medico");
            }


        } catch (SQLException e) {
            Message.warning(this, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboEsp = new javax.swing.JComboBox<>();
        comboMedico = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dateAppt = new com.toedter.calendar.JDateChooser();
        hourAppt = new javax.swing.JSpinner();

        setClosable(true);
        setIconifiable(true);
        setTitle("Crear cita");

        jLabel1.setText("Dni");

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });

        jLabel2.setText("Especialidad");

        jLabel3.setText("Hora de cita");

        jLabel4.setText("Fecha de cita");

        jLabel5.setText("Médico");

        comboEsp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Motivo");

        jButton1.setIcon(new javax.swing.ImageIcon("F:\\jackzinho\\appclinicsystem\\icons\\crear.png")); // NOI18N
        jButton1.setText("Crear");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("F:\\jackzinho\\appclinicsystem\\icons\\salir.png")); // NOI18N
        jButton2.setText("Salir");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(jLabel4)
                                .addComponent(comboEsp, 0, 100, Short.MAX_VALUE)
                                .addComponent(dateAppt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(comboMedico, 0, 100, Short.MAX_VALUE)
                            .addComponent(jButton2)
                            .addComponent(hourAppt)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel5))
                    .addComponent(txtDni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(txtMotivo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateAppt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourAppt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(16, 16, 16))
        );

        txtDni.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String dni = txtDni.getText().trim();
            String medico = (String) comboMedico.getSelectedItem();
            Date date = dateAppt.getDate();

            Date startHour = (Date) hourAppt.getValue();
            SimpleDateFormat sdfHour = new SimpleDateFormat("HH");
            String horaFinStr = sdfHour.format(startHour) + ":00:00";
            Time time = Time.valueOf(horaFinStr);

            String reason = txtMotivo.getText().trim();

            if (this.businessAppt.insert(dni, medico, date, time, reason, "confirmada", "offline")) {
                Message.success(this, "La cita se realizó exitosamente");
            }
        } catch (IllegalArgumentException | SQLException e) {
            Message.warning(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboEsp;
    private javax.swing.JComboBox<String> comboMedico;
    private com.toedter.calendar.JDateChooser dateAppt;
    private javax.swing.JSpinner hourAppt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtMotivo;
    // End of variables declaration//GEN-END:variables
}
