/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.epiis.app.presentation;

import com.epiis.app.business.BusinessConsultation;
import com.epiis.app.business.BusinessPatient;
import com.epiis.app.config.Message;
import com.epiis.app.dto.DtoConsultation;
import com.epiis.app.dto.DtoPatient;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhona
 */
public class FrmClinicalHistory extends javax.swing.JInternalFrame {
    DtoPatient dtoPatient = null;
    BusinessPatient businessPatient = null;
    BusinessConsultation businessConsultation  = null;
    
    // Modelo de tabla
    private final DefaultTableModel dtmTablePerson = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            // Solo la columna de acciones es editable
            return column == 6;
        }
    };
    /**
     * Creates new form FrmClinicalHistory
     */
    public FrmClinicalHistory(DtoPatient dtoPatient) {
        this.dtoPatient = dtoPatient;
        this.businessConsultation = new BusinessConsultation();
        initComponents();
        this.init();
    }
       
    // historial clinico: tappointment ⟶ tconsultation ⟶ tprescription ⟶ temployee + tspecialty
    //                  : cita            consulta médica   receta           medico + espcecialidad
    private void init() {
        try {
            this.businessPatient = new BusinessPatient();
            List<DtoConsultation> listDtoConsultations = this.businessConsultation.getAll();

            this.tableHistory.setModel(dtmTablePerson);

            this.dtmTablePerson.addColumn("ID");
            this.dtmTablePerson.addColumn("Fecha de cita");
            this.dtmTablePerson.addColumn("Estado");
            this.dtmTablePerson.addColumn("Médico");
            this.dtmTablePerson.addColumn("Fecha consulta");
            this.dtmTablePerson.addColumn("Diagnostico");
            this.dtmTablePerson.addColumn("Tratamiento");

            for (DtoConsultation item : listDtoConsultations) {
                this.dtmTablePerson.addRow(new Object[]{
                    item.getIdConsultation(),
                    item.getDtoAppt().getApptDate() + " " + item.getDtoAppt().getApptTime(),
                    item.getDtoAppt().getStatus(),
                    item.getDtoEmployee().getFirstName(),
                    item.getCreatedAt(),
                    item.getDiagnosis(),
                    item.getTreatment(),
                });
            }

            this.tableHistory.removeColumn(this.tableHistory.getColumnModel().getColumn(0));

            // Asignar una sola columna de botones
            /*ButtonActionRendererEditor actionButtonRenderer = new ButtonActionRendererEditor(tablePerson);
            this.tablePerson.getColumn("Acciones").setCellRenderer(actionButtonRenderer);
            this.tablePerson.getColumn("Acciones").setCellEditor(actionButtonRenderer);*/

        } catch (SQLException ex) {
            Message.error(this, ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHistory = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setTitle("Mi historial clinica");

        jLabel1.setText("Filtrar por estado");

        jScrollPane1.setViewportView(tableHistory);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        jLabel2.setText("Historial clinico");

        jLabel3.setText("Buscar por fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableHistory;
    // End of variables declaration//GEN-END:variables
}
