/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.epiis.app.presentation;

import com.epiis.app.dto.DtoEmployee;
import javax.swing.JFrame;

/**
 *
 * @author USUARIO
 */
public class FrmDashboardAdmin extends javax.swing.JFrame {
    DtoEmployee dtoEmployee = null;
    /**
     * Creates new form FrmDashboardAdm
     */
    public FrmDashboardAdmin(DtoEmployee dtoEmployee) {
        this.dtoEmployee = dtoEmployee;
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     **/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        menuBar = new javax.swing.JMenuBar();
        menuPerfil = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        menuPacientes = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de control administrativo");

        jLabel1.setText("Reportes de dia");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(30, 30, 260, 16);

        jScrollPane1.setViewportView(jList1);

        desktopPane.add(jScrollPane1);
        jScrollPane1.setBounds(30, 50, 270, 110);

        menuPerfil.setIcon(new javax.swing.ImageIcon("F:\\jackzinho\\appclinicsystem\\icons\\perfil.png")); // NOI18N
        menuPerfil.setMnemonic('f');
        menuPerfil.setText("Perfil");
        menuPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem5.setText("Editar perfil");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuPerfil.add(jMenuItem5);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Cerrar sesión");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        menuPerfil.add(exitMenuItem);

        menuBar.add(menuPerfil);

        menuUsuario.setIcon(new javax.swing.ImageIcon("F:\\jackzinho\\appclinicsystem\\icons\\usuarios.png")); // NOI18N
        menuUsuario.setMnemonic('e');
        menuUsuario.setText("Usuario");
        menuUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem1.setText("Gestión de recepcionistas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuUsuario.add(jMenuItem1);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Gestión de médicos");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        menuUsuario.add(deleteMenuItem);

        menuBar.add(menuUsuario);

        menuPacientes.setIcon(new javax.swing.ImageIcon("F:\\jackzinho\\appclinicsystem\\icons\\paciente.png")); // NOI18N
        menuPacientes.setMnemonic('h');
        menuPacientes.setText("Paciente");
        menuPacientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuPacientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Gestión de pacientes");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        menuPacientes.add(contentMenuItem);

        menuBar.add(menuPacientes);

        jMenu7.setIcon(new javax.swing.ImageIcon("F:\\jackzinho\\appclinicsystem\\icons\\cita.png")); // NOI18N
        jMenu7.setText("Cita");
        jMenu7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem2.setText("Ver toda las citas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        menuBar.add(jMenu7);

        jMenu5.setIcon(new javax.swing.ImageIcon("F:\\jackzinho\\appclinicsystem\\icons\\servicio.png")); // NOI18N
        jMenu5.setText("Servicio");
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem3.setText("Gestionar servicios");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        menuBar.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon("F:\\jackzinho\\appclinicsystem\\icons\\especialidad.png")); // NOI18N
        jMenu6.setText("Especialidad");
        jMenu6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem4.setText("Gestionar especialidades");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        menuBar.add(jMenu6);

        menuReportes.setIcon(new javax.swing.ImageIcon("F:\\jackzinho\\appclinicsystem\\icons\\reporte.png")); // NOI18N
        menuReportes.setText("Reportes");
        menuReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuBar.add(menuReportes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        FrmUpdateUser frmUpdateUser = new FrmUpdateUser(dtoEmployee);
        desktopPane.add(frmUpdateUser);
        frmUpdateUser.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
        FrmGetAllPatient frmGetAllPatient = new FrmGetAllPatient();
        desktopPane.add(frmGetAllPatient);
        frmGetAllPatient.setVisible(true);
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitMenuItemActionPerformed
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }// GEN-LAST:event_exitMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FrmGetAllRecep r = new FrmGetAllRecep();
        desktopPane.add(r);
        r.setVisible(true);
    }// GEN-LAST:event_jMenuItem1ActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteMenuItemActionPerformed
        // TODO add your handling code here:
        FrmGetAllMedico m = new FrmGetAllMedico();
        desktopPane.add(m);
        m.setVisible(true);
    }// GEN-LAST:event_deleteMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FrmGetAllAppt c = new FrmGetAllAppt();
        desktopPane.add(c);
        c.setVisible(true);
    }// GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        FrmAddSpecialty e = new FrmAddSpecialty();
        desktopPane.add(e);
        e.setVisible(true);
    }// GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        FrmAddService s = new FrmAddService();
        desktopPane.add(s);
        s.setVisible(true);
    }// GEN-LAST:event_jMenuItem3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuPacientes;
    private javax.swing.JMenu menuPerfil;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuUsuario;
    // End of variables declaration//GEN-END:variables

}
