/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.epiis.app.presentation;

import com.epiis.app.business.BusinessApptRequet;
import com.epiis.app.dto.DtoApptRequest;
import com.epiis.app.dto.DtoEmployee;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class FrmDashboardRecep extends javax.swing.JFrame {
    DtoEmployee dtoEmployee = null;
    BusinessApptRequet apptRequet = null;
    LocalDate today = LocalDate.now(); // fecha actual del sistema

    private final DefaultTableModel dtmTablePerson = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column == 8;
        }
    };
    /**
     * Creates new form FrmDashboardRecep
     */
    public FrmDashboardRecep(DtoEmployee dtoEmployee) {
        this.dtoEmployee = dtoEmployee;
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.init();
    }
    
    private void init() {
        try {
            this.apptRequet = new BusinessApptRequet(); 
            List<DtoApptRequest> listAppt = this.apptRequet.getAllPatient();
            
            this.tableAppt.setModel(dtmTablePerson);

            this.dtmTablePerson.addColumn("Dni");
            this.dtmTablePerson.addColumn("Nombre completo");
            this.dtmTablePerson.addColumn("Médico");
            this.dtmTablePerson.addColumn("Fecha cita");
            this.dtmTablePerson.addColumn("Motivo");
            this.dtmTablePerson.addColumn("Estado");
            this.dtmTablePerson.addColumn("Fecha solicitada");
            this.dtmTablePerson.addColumn("Confirmar");
            this.dtmTablePerson.addColumn("Rechazar");

            for (DtoApptRequest item : listAppt) {
                LocalDate requestDate = new java.sql.Date(item.getRequestDate().getTime())
                            .toLocalDate();

                if(item.getStatus().equals("pendiente") && requestDate.equals(today)){
                    this.dtmTablePerson.addRow(new Object[]{
                        item.getDtoPatient().getDni(),
                        item.getDtoPatient().getFirstName() + " " + item.getDtoPatient().getSurNameP() + " " + item.getDtoPatient().getSurNameM(),
                        item.getDtoEmployee().getFirstName(),
                        item.getRequestDate()+ " " + item.getRequestTime(),
                        item.getReason(),
                        item.getStatus(),
                        item.getCreatedAt(),
                        "Confirmar",
                        "Rechazar"
                    });
                }
            }


        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(this, "Error al cargar datos: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAppt = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de control de recepcionista");

        jScrollPane1.setViewportView(tableAppt);

        desktopPane.add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 680, 210);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Citas solicitadas para hoy");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(20, 10, 590, 25);

        fileMenu.setIcon(new javax.swing.ImageIcon("E:\\jackzinho\\appclinicsystem\\icons\\perfil.png")); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("Perfil");
        fileMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fileMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Editar perfil");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Cerrar sesión");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setIcon(new javax.swing.ImageIcon("E:\\jackzinho\\appclinicsystem\\icons\\paciente.png")); // NOI18N
        editMenu.setMnemonic('e');
        editMenu.setText("Pacientes");
        editMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Registrar pacientes");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        menuBar.add(editMenu);

        helpMenu.setIcon(new javax.swing.ImageIcon("E:\\jackzinho\\appclinicsystem\\icons\\cita.png")); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Citas");
        helpMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        helpMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Crear cita");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Gestionar cita");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        jMenu1.setIcon(new javax.swing.ImageIcon("E:\\jackzinho\\appclinicsystem\\icons\\reporte.png")); // NOI18N
        jMenu1.setText("Reportes");
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem2.setText("Crear reportes");
        jMenu1.add(jMenuItem2);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        FrmUpdateUser updateUser = new FrmUpdateUser(this.dtoEmployee);
        desktopPane.add(updateUser);
        updateUser.setVisible(true);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
        FrmAddAppt addAppt = new FrmAddAppt();
        desktopPane.add(addAppt);
        addAppt.setVisible(true);
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        FrmManageAppt manageAppt = new FrmManageAppt();
        desktopPane.add(manageAppt);
        manageAppt.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        FrmAddPatient addPatient = new FrmAddPatient();
        desktopPane.add(addPatient);
        addPatient.setVisible(true);
    }//GEN-LAST:event_cutMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JTable tableAppt;
    // End of variables declaration//GEN-END:variables

}
