/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.epiis.app.presentation;

import com.epiis.app.business.BusinessApptRequet;
import com.epiis.app.config.Message;
import com.epiis.app.dto.DtoApptRequest;
import com.epiis.app.dto.DtoPatient;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhona
 */
public class FrmManageApptPatient extends javax.swing.JInternalFrame {
    DtoPatient dtoPatient = null;
    BusinessApptRequet businessApptRequet = null;
    
    private final DefaultTableModel dtmTablePerson = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column == 5;
        }
    };
    /**
     * Creates new form FrmManageApptPatient
     * @param dtoPatient
     */
    public FrmManageApptPatient(DtoPatient dtoPatient) {
        this.dtoPatient = dtoPatient;
        initComponents();
        this.init();
    }
    
    private void init() {
        try {
            this.businessApptRequet = new BusinessApptRequet();
            List<DtoApptRequest> listDtoPerson = this.businessApptRequet.getAll();

            this.tableAppt.setModel(dtmTablePerson);

            this.dtmTablePerson.addColumn("Fecha de cita");
            this.dtmTablePerson.addColumn("Hora de cita");
            this.dtmTablePerson.addColumn("motivo");
            this.dtmTablePerson.addColumn("Estado");
            this.dtmTablePerson.addColumn("Fecha solicitada");

            for (DtoApptRequest item : listDtoPerson) {
                if(item.getDtoPatient().getIdPatient().equals(this.dtoPatient.getIdPatient()) && item.getStatus().equalsIgnoreCase("pendiente")){
                    this.dtmTablePerson.addRow(new Object[]{
                        item.getRequestDate(),
                        item.getRequestTime(),
                        item.getReason(),
                        item.getStatus(),
                        item.getCreatedAt(),
                    });
                }
            }

        } catch (SQLException ex) {
            Message.error(this, ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAppt = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gestionar mis citas");

        jLabel1.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        jLabel1.setText("Mis citas pendientes");

        jScrollPane1.setViewportView(tableAppt);

        jMenu1.setIcon(new javax.swing.ImageIcon("F:\\jackzinho\\appclinicsystem\\icons\\reserva.png")); // NOI18N
        jMenu1.setText("Reservar");
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem1.setText("Reservar cita");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("F:\\jackzinho\\appclinicsystem\\icons\\reprogramar.png")); // NOI18N
        jMenu2.setText("Reprogramar");
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem2.setText("Reprogramar cita");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FrmAddApptPatient apptPatient = new FrmAddApptPatient(this.dtoPatient);
        FrmClinica.desktopPane.add(apptPatient);
        apptPatient.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FrmReschedule frmReschedule = new FrmReschedule(this.dtoPatient);
        FrmClinica.desktopPane.add(frmReschedule);
        frmReschedule.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAppt;
    // End of variables declaration//GEN-END:variables
}
